remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
github:
  repository_url: "https://github.com/aqualinkd"
title: [AqualinkD]
description: [Control Jandy RS Aqualink pool equiptment]
